[package]
name = "LearningToolRS"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.25.0"
tui = "0.19.0"
tracing = "0.1"
tracing-subscriber = "0.3"
structopt = "0.3.26"
