= Learning Tool RS

image:https://github.com/phughk/LearningToolRS/actions/workflows/rust.yml/badge.svg[Rust Status]
https://github.com/phughk/LearningToolRS/actions/workflows/rust.yml[Rust Link]

Learning Tool RS is a rust implementation of a tool that allows for learning various concepts.

== Build

[source]
----
cargo run
----

== Design
Program execution is as follows

. Launch, pointing at repositories, thus handling separate users and modular datasets
. List available datasets and pick one
. Decide to review stats, dataset info, or pick
. Decide exit conditions of learning session (number of questions, number of loops, progress target, drop off ratios)
. Review final score and stats
. Back to main menu

== Types of questions

Text:

. Flip-card (question shown, answer hidden - no point counting)
. True/False
. Single answer from list
.. Property combinations
.. Symmetric questions ("In Rust, what's another term for reference", "... another term for borrow")
. Multiple answer from list
. Free-text
.. Exact match
.. Exact match numeric
.. Within range numeric
.. Subset match
.. NLP match
.. Accent match
.. Phrase completion. "When a metric becomes a goal it ceases to..."be a reliable metric"
. Audio match (Duolingo style)
. Reverse
. Pairing
. Order of list items (ex sequence of events)
. Multiple categories (ex. list to 3 categories)


Graphics:

Sound:
. Text match

Animation:

== User Interface
(Generated with https://asciiflow.com/#/ ).

=== Module browser

Once started, the user is presented with a screen where the available modules are presented to them.
They can use the arrow keys to browse the dataset modules.
Pressing enter will pick the module to proceed to the main screen.

```
┌────────────────────────────────────────────────────────────┐
│Current Directory                                           │
├──────────────────────────────┬─────────────────────────────┤
│                              │                             │
│   Entry 1                    │  Module stats               │
│                              │                             │
│   Entry 2                    │    Last played              │
│                              │                             │
│   Entry 3                    │    Last score               │
│                              │                             │
│                              │    Progres                  │
│                              │                             │
│                              │    ETA completion           │
│                              │                             │
└──────────────────────────────┴─────────────────────────────┘
```

=== Quiz setup screen

When a dataset has been picked, it must be configured for termination conditions.

```
┌────────────────────────────────────────────────────────────┐
│ Module name                                                │
├──────────────────────────────┬─────────────────────────────┤
│                              │                             │
│  Option 1                    │  Module stats               │
│  Input 1                     │                             │
│                              │    Last played              │
│  Option 2                    │                             │
│  Input 2                     │    Last score               │
│                              │                             │
│                              │    Progres                  │
│                              │                             │
│                              │    ETA completion           │
│                              │                             │
└──────────────────────────────┴─────────────────────────────┘
```

=== Quiz screen loop

Once the game has been set up, the game loop can begin.


```
 ┌────────────────────────────────────────────────────────────┐
 │ Module name                                                │
 ├────────────────────────────────────────────────────────────┤
 │                                                            │
 │             Question example goes here?                    │
 │                                                            │
 │                                                            │
 │                                                            │
 │  A  Prompt 1                         C Prompt 3            │
 │                                                            │
 │  B  Prompt 2                         D Prompt 4            │
 │                                                            │
 ├────────────────────────────────────────────────────────────┤
 │ Progress stats go here                                     │
 └────────────────────────────────────────────────────────────┘
```

=== Quiz score

=== Quiz historic stats view

