= Learning Tool RS

image:https://github.com/phughk/LearningToolRS/actions/workflows/rust.yml/badge.svg[Rust Status]
https://github.com/phughk/LearningToolRS/actions/workflows/rust.yml[Rust Link]

Learning Tool RS is a rust implementation of a tool that allows for learning various concepts.

== Build

[source]
----
cargo run
----

== Design
Program execution is as follows

. Launch, pointing at repositories, thus handling separate users and modular datasets
. List available datasets and pick one
. Decide to review stats, dataset info, or pick
. Decide exit conditions of learning session (number of questions, number of loops, progress target, drop off ratios)
. Review final score and stats
. Back to main menu

== Types of questions

Text:

. True/False
. Single answer from list
. Multiple answer from list
. Free-text
.. Exact match
.. Exact match numeric
.. Within range numeric
.. Subset match
.. NLP match
.. Accent match
. Audio match (Duolingo style)
. Reverse
. Pairing
. Order of list items
. Multiple categories (ex. list to 3 categories)


Graphics:

Sound:
. Text match

Animation: